name: continuous-integration
on: [push]
jobs:
  build:
    name: yarn-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: bootstrap
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test